### ISSUE TITLE
Questions about How to Use

### ISSUE THREAD

**Issue by LucasCioffi** [exciting-io/slack-bot-server#3]
Hello, thanks for writing this gem.  

I'm looking through the documentation and these are the questions that come to mind:

1. To use Foreman to start the SimpleBot server, I'm assuming we add a line to the Procfile.  What would that line look like?

2. For the Advanced Example to work, do we have to install anything extra such as a Gem to make Harmonia work?  In other words, what is this connecting to...

    require 'harmonia/slack_bot'

**Comment by lazyatom** [comment]
Assuming that you've followed the README (https://github.com/exciting-io/slack-bot-server#usage) and created your own short script, saved as `bin/slack_server`, this would be a typical line for your `Procfile`:

```
slack_server: bundle exec rails runner bin/slack_server
```

Regarding the advanced example, if I understand your question correctly, I think you're hoping that you'll actually be able to run that code; unfortunately, that won't quite work. The `harmonia/slack_bot` file referenced in the advanced example is not something you can actually use -- Harmonia's source code is private.

That line is meant to demonstrate that you can require a Ruby file that you've written from someone in an existing application of your own, and use the classes defined there inside the `on_new_token` block to create bots that behave appropriately for your application.

Does that clear it up for you?

**Comment by LucasCioffi** [comment]
Very clear.  Thank you!!  Congrats on a great gem.

**Comment by LucasCioffi** [comment]
Unfortunately I did run into `uninitialized constant Slack::Client` on the server.  It was caused when I ran `slack_remote.add_token('my_bot_token')` in the console (output is pasted under the server log below).  I had `redis-server` running in a third terminal tab.

````
$ foreman start
23:27:08 web.1          | started with pid 1743
23:27:08 slack_server.1 | started with pid 1744
23:27:09 web.1          | [1743] Puma starting in cluster mode...
23:27:09 web.1          | [1743] * Version 2.15.3 (ruby 2.2.0-p0), codename: Autumn Arbor Airbrush
23:27:09 web.1          | [1743] * Min threads: 1, max threads: 1
23:27:09 web.1          | [1743] * Environment: development
23:27:09 web.1          | [1743] * Process workers: 2
23:27:09 web.1          | [1743] * Preloading application
23:27:14 web.1          | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/slack-api-1.2.0/lib/slack/version.rb:2: warning: already initialized constant Slack::VERSION
23:27:14 web.1          | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/slack-ruby-client-0.5.0/lib/slack/version.rb:2: warning: previous definition of VERSION was here
23:27:15 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/slack-api-1.2.0/lib/slack/version.rb:2: warning: already initialized constant Slack::VERSION
23:27:15 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/slack-ruby-client-0.5.0/lib/slack/version.rb:2: warning: previous definition of VERSION was here
23:27:16 web.1          | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/actionpack-4.2.0/lib/action_dispatch/http/mime_type.rb:163: warning: already initialized constant Mime::ICS
23:27:16 web.1          | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/actionpack-4.2.0/lib/action_dispatch/http/mime_type.rb:163: warning: previous definition of ICS was here
23:27:16 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/actionpack-4.2.0/lib/action_dispatch/http/mime_type.rb:163: warning: already initialized constant Mime::ICS
23:27:16 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/actionpack-4.2.0/lib/action_dispatch/http/mime_type.rb:163: warning: previous definition of ICS was here
23:27:17 web.1          | [1743] * Listening on tcp://0.0.0.0:5000
23:27:17 web.1          | [1743] ! WARNING: Detected 2 Thread(s) started in app boot:
23:27:17 web.1          | [1743] ! #<Thread:0x007f97e02827b8@/Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/minitest-5.5.1/lib/minitest/parallel.rb:21 sleep> - /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/minitest-5.5.1/lib/minitest/parallel.rb:23:in `pop'
23:27:17 web.1          | [1743] ! #<Thread:0x007f97e0282d08@/Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/minitest-5.5.1/lib/minitest/parallel.rb:21 sleep> - /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/minitest-5.5.1/lib/minitest/parallel.rb:23:in `pop'
23:27:17 web.1          | [1743] Use Ctrl-C to stop
23:27:17 web.1          | [1743] - Worker 0 (pid: 1775) booted, phase: 0
23:27:17 web.1          | [1743] - Worker 1 (pid: 1776) booted, phase: 0
23:27:39 slack_server.1 | I, [2015-12-10T23:27:39.754326 #1744]  INFO -- : got new token: 'my_bot_token'
23:27:39 slack_server.1 | W, [2015-12-10T23:27:39.755652 #1744]  WARN -- : Error in server: uninitialized constant Slack::Client - uninitialized constant Slack::Client
23:27:39 slack_server.1 | W, [2015-12-10T23:27:39.755708 #1744]  WARN -- : /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/slack-bot-server-0.1.2/lib/slack_bot_server/bot.rb:11:in `initialize'
23:27:39 slack_server.1 | bin/slack_server:19:in `new'
23:27:39 slack_server.1 | bin/slack_server:19:in `block in <top (required)>'
23:27:39 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/slack-bot-server-0.1.2/lib/slack_bot_server/server.rb:53:in `call'
23:27:39 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/slack-bot-server-0.1.2/lib/slack_bot_server/server.rb:53:in `add_token'
23:27:39 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/slack-bot-server-0.1.2/lib/slack_bot_server/server.rb:76:in `process_instruction'
23:27:39 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/slack-bot-server-0.1.2/lib/slack_bot_server/server.rb:31:in `block in add_timers'
23:27:39 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/eventmachine-1.0.8/lib/em/timers.rb:56:in `call'
23:27:39 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/eventmachine-1.0.8/lib/em/timers.rb:56:in `fire'
23:27:39 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `call'
23:27:39 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run_machine'
23:27:39 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run'
23:27:39 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/slack-bot-server-0.1.2/lib/slack_bot_server/server.rb:20:in `start'
23:27:39 slack_server.1 | bin/slack_server:24:in `<top (required)>'
23:27:39 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/railties-4.2.0/lib/rails/commands/runner.rb:60:in `load'
23:27:39 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/railties-4.2.0/lib/rails/commands/runner.rb:60:in `<top (required)>'
23:27:39 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:123:in `require'
23:27:39 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
23:27:39 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:90:in `runner'
23:27:39 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
23:27:39 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
23:27:39 slack_server.1 | bin/rails:4:in `require'
23:27:39 slack_server.1 | bin/rails:4:in `<main>'
````

````
$ rails c
/Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/slack-api-1.2.0/lib/slack/version.rb:2: warning: already initialized constant Slack::VERSION
/Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/slack-ruby-client-0.5.0/lib/slack/version.rb:2: warning: previous definition of VERSION was here
/Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/actionpack-4.2.0/lib/action_dispatch/http/mime_type.rb:163: warning: already initialized constant Mime::ICS
/Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/actionpack-4.2.0/lib/action_dispatch/http/mime_type.rb:163: warning: previous definition of ICS was here
Loading development environment (Rails 4.2.0)
2.2.0 :001 > require 'slack_bot_server'
 => true 
2.2.0 :002 > require 'slack_bot_server/redis_queue'
 => false 
2.2.0 :003 > require 'slack_bot_server/simple_bot'
 => false 
2.2.0 :004 > require 'slack_bot_server/remote_control'
/Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/slack-bot-server-0.1.2/lib/slack_bot_server/remote_control.rb:8: warning: circular argument reference - queue
 => true 
2.2.0 :005 > queue = SlackBotServer::RedisQueue.new(Redis.new)
 => #<SlackBotServer::RedisQueue:0x007fd482490bc0 @key="slack_bot_server:queue", @redis=#<Redis client v3.2.2 for redis://127.0.0.1:6379/0>> 
2.2.0 :006 > slack_remote = SlackBotServer::RemoteControl.new(queue: queue)
 => #<SlackBotServer::RemoteControl:0x007fd482461c80 @queue=#<SlackBotServer::RedisQueue:0x007fd482490bc0 @key="slack_bot_server:queue", @redis=#<Redis client v3.2.2 for redis://127.0.0.1:6379/0>>> 
2.2.0 :007 > slack_remote.add_token('my_bot_token')
 => 1 
2.2.0 :008 > slack_remote.add_token('my_bot_token')
 => 1 
2.2.0 :009 > 
````

**Comment by LucasCioffi** [comment]
Question 2: To get the API Token, is it necessary to create the bot at `https://my_subdomain.slack.com/services/new/bot` first and use the API token in `slack_remote.add_token('my_bot_token')`?

Or should we get the API Token on this page https://api.slack.com/web which lets me create a token for any team I administer.

**Comment by lazyatom** [comment]
You'll need to create a bot and use the token for that bot.

**Comment by LucasCioffi** [comment]
Thank you for clarifying; I assumed creating a bot was necessary.

Any idea what might cause the `uninitialized constant Slack::Client` error in the comment labeled Question #1 above?

**Comment by lazyatom** [comment]
I think this is caused by your usage of both `slack-ruby-client` (which presumably you've added to your `Gemfile`) and `slack-api` (which `slack-bot-server` requires). Both of these gems define have a file which can be loaded via `require "slack"`, unfortunately.

In the short term, at the start of your `bin/slack_server` file (or whatever you've called it), you could add `require "slack/client"` and I *think* this should resolve it. I will also make the require more explicit in this gem, which should hopefully also resolve it.

Hopefully there are no other negative interactions between `slack-ruby-client` and `slack-api`.

**Comment by lazyatom** [comment]
I've released `v0.1.3` with this fix.

**Comment by LucasCioffi** [comment]
Thank you for `v0.1.3`.

I can confirm it was the gem called `slack-ruby-client` that has the conflict.  When I commented it out, SimpleBot worked.  Woohoo!

I'm guessing that this gem can do everything that `slack-ruby-client` can do, so maybe I should just continue to keep it commented out and translate my previous controller actions with that gem into this gem since this gem handles multiple bots.

In case it's worth fixing so that people can use both, this is the new error I'm getting when `slack-ruby-client` is not commented out:
```
09:35:03 slack_server.1 | W, [2015-12-11T09:35:03.904536 #991]  WARN -- : Error in server: undefined method `options' for Slack:Module - undefined method `options' for Slack:Module
09:35:03 slack_server.1 | W, [2015-12-11T09:35:03.905700 #991]  WARN -- : /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/slack-api-1.2.1/lib/slack/api.rb:15:in `initialize'
```

Full Log:
```
$ foreman start
09:34:25 web.1          | started with pid 989
09:34:26 slack_server.1 | started with pid 991
09:34:27 web.1          | [989] Puma starting in cluster mode...
09:34:27 web.1          | [989] * Version 2.15.3 (ruby 2.2.0-p0), codename: Autumn Arbor Airbrush
09:34:27 web.1          | [989] * Min threads: 1, max threads: 1
09:34:27 web.1          | [989] * Environment: development
09:34:27 web.1          | [989] * Process workers: 2
09:34:27 web.1          | [989] * Preloading application
09:34:35 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/slack-api-1.2.1/lib/slack/version.rb:2: warning: already initialized constant Slack::VERSION
09:34:35 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/slack-ruby-client-0.5.0/lib/slack/version.rb:2: warning: previous definition of VERSION was here
09:34:35 web.1          | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/slack-api-1.2.1/lib/slack/version.rb:2: warning: already initialized constant Slack::VERSION
09:34:35 web.1          | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/slack-ruby-client-0.5.0/lib/slack/version.rb:2: warning: previous definition of VERSION was here
09:34:37 web.1          | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/actionpack-4.2.0/lib/action_dispatch/http/mime_type.rb:163: warning: already initialized constant Mime::ICS
09:34:37 web.1          | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/actionpack-4.2.0/lib/action_dispatch/http/mime_type.rb:163: warning: previous definition of ICS was here
09:34:37 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/actionpack-4.2.0/lib/action_dispatch/http/mime_type.rb:163: warning: already initialized constant Mime::ICS
09:34:37 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/actionpack-4.2.0/lib/action_dispatch/http/mime_type.rb:163: warning: previous definition of ICS was here
09:34:39 web.1          | [989] * Listening on tcp://0.0.0.0:5000
09:34:39 web.1          | [989] ! WARNING: Detected 2 Thread(s) started in app boot:
09:34:39 web.1          | [989] ! #<Thread:0x007fd2a9d6be50@/Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/minitest-5.5.1/lib/minitest/parallel.rb:21 sleep> - /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/minitest-5.5.1/lib/minitest/parallel.rb:23:in `pop'
09:34:39 web.1          | [989] ! #<Thread:0x007fd2a9d70090@/Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/minitest-5.5.1/lib/minitest/parallel.rb:21 sleep> - /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/minitest-5.5.1/lib/minitest/parallel.rb:23:in `pop'
09:34:39 web.1          | [989] Use Ctrl-C to stop
09:34:39 web.1          | [989] - Worker 0 (pid: 1522) booted, phase: 0
09:34:39 web.1          | [989] - Worker 1 (pid: 1523) booted, phase: 0
09:35:03 slack_server.1 | I, [2015-12-11T09:35:03.904387 #991]  INFO -- : got new token: '[my_token_goes_here]'
09:35:03 slack_server.1 | W, [2015-12-11T09:35:03.904536 #991]  WARN -- : Error in server: undefined method `options' for Slack:Module - undefined method `options' for Slack:Module
09:35:03 slack_server.1 | W, [2015-12-11T09:35:03.905700 #991]  WARN -- : /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/slack-api-1.2.1/lib/slack/api.rb:15:in `initialize'
09:35:03 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/slack-bot-server-0.1.3/lib/slack_bot_server/bot.rb:12:in `new'
09:35:03 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/slack-bot-server-0.1.3/lib/slack_bot_server/bot.rb:12:in `initialize'
09:35:03 slack_server.1 | bin/slack_server:19:in `new'
09:35:03 slack_server.1 | bin/slack_server:19:in `block in <top (required)>'
09:35:03 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/slack-bot-server-0.1.3/lib/slack_bot_server/server.rb:53:in `call'
09:35:03 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/slack-bot-server-0.1.3/lib/slack_bot_server/server.rb:53:in `add_token'
09:35:03 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/slack-bot-server-0.1.3/lib/slack_bot_server/server.rb:76:in `process_instruction'
09:35:03 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/slack-bot-server-0.1.3/lib/slack_bot_server/server.rb:31:in `block in add_timers'
09:35:03 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/eventmachine-1.0.8/lib/em/timers.rb:56:in `call'
09:35:03 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/eventmachine-1.0.8/lib/em/timers.rb:56:in `fire'
09:35:03 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `call'
09:35:03 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run_machine'
09:35:03 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run'
09:35:03 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/slack-bot-server-0.1.3/lib/slack_bot_server/server.rb:20:in `start'
09:35:03 slack_server.1 | bin/slack_server:24:in `<top (required)>'
09:35:03 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/railties-4.2.0/lib/rails/commands/runner.rb:60:in `load'
09:35:03 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/railties-4.2.0/lib/rails/commands/runner.rb:60:in `<top (required)>'
09:35:03 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:123:in `require'
09:35:03 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
09:35:03 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:90:in `runner'
09:35:03 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
09:35:03 slack_server.1 | /Users/lucas/.rvm/gems/ruby-2.2.0@test/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
09:35:03 slack_server.1 | bin/rails:4:in `require'
09:35:03 slack_server.1 | bin/rails:4:in `<main>'
```

**Comment by lazyatom** [comment]
I think you might now need to remove your explicit require to `slack/client`.

**Comment by LucasCioffi** [comment]
With the `gem 'slack-ruby-client'` commented out, everything works fine whether or not `require "slack/client"` is present in the `slack_server` file, so I'll keep it out as you suggested.  Thanks again.
